import turtle
import time
def drawGap():
    turtle.penup()
    turtle.fd(2)
def drawLine(draw):
    drawGap()
    turtle.pendown() if draw else turtle.penup()
    turtle.fd(10)
    drawGap()
    turtle.right(90)
def drawDigit(digit):
    drawLine(True) if digit in [2,3,4,5,6,8,9] else drawLine(False)
    drawLine(True) if digit in [0,1,3,4,5,6,7,8,9] else drawLine(False)
    drawLine(True) if digit in [0,2,3,5,6,8,9] else drawLine(False)
    drawLine(True) if digit in [0,2,6,8] else drawLine(False)
    turtle.left(90)
    drawLine(True) if digit in [0,4,5,6,8,9] else drawLine(False)
    drawLine(True) if digit in [0,2,3,5,6,7,8,9] else drawLine(False)
    drawLine(True) if digit in [0,1,2,3,4,7,8,9] else drawLine(False)
    turtle.left(180)
    turtle.penup()
    turtle.fd(20)
def drawDate(date):
    turtle.pencolor("red")
    for i in date:
        if i == "-":
            turtle.write("年",font = ("Arial",18,"normal"))
            turtle.pencolor("green")
            turtle.fd(20)
        elif i == '=':
            turtle.write("月",font = ("Arial",18,"normal"))
            turtle.pencolor("blue")
            turtle.fd(40)
        elif i == "+":
            turtle.write("日",font = ("Arial",18,"normal"))
        else:
            drawDigit(eval(i))
def main():
    turtle.setup(800,350,200,200)
    turtle.pensize(5)
    turtle.pencolor("red")
    turtle.penup()
    turtle.fd(-300)
    turtle.pendown()
    turtle.write("小",font = ("Arial",18,"normal"))
    turtle.penup()
    turtle.fd(30)
    turtle.pendown()
    turtle.write("峰",font = ("Arial",18,"normal"))
    turtle.penup()
    turtle.fd(30)
    turtle.pendown()
    turtle.write("峰",font = ("Arial",18,"normal"))
    turtle.penup()
    turtle.fd(70)
    turtle.pendown()
    turtle.write("I",font = ("Arial",18,"normal"))
    turtle.penup()
    turtle.fd(50)
    turtle.pendown()
    turtle.write("Love",font = ("Arial",18,"normal"))
    turtle.penup()
    turtle.fd(80)
    turtle.pendown()
    turtle.write("You",font = ("Arial",18,"normal"))
    turtle.penup()
    turtle.right(90)
    turtle.fd(140)
    turtle.left(90)
    drawDate(time.strftime("%Y-%m=%d+",time.gmtime()))
    turtle.hideturtle()
    turtle.done()
main()